include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'test/.test_coverage.dart'

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_single_quotes: true
    public_member_api_docs: false
