name: iyzipay
description: iyzipay api dart client.
version: 1.0.0
repository: https://github.com/sametdmr/iyzipay

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  http: ^0.13.5
  json_annotation: ^4.7.0
  meta: ^1.8.0
  pointycastle: ^3.6.2

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  test: ^1.16.0
  very_good_analysis: ^3.1.0
